# PANDAS - PANel DAta Structure

**Retail Sales Dataset**

In [1]:
#import the libraries
import pandas as pd
import numpy as np

In [37]:
#creating a dataset in a dictionary format (key = columns, values = rows)
data = {
    "Order_ID": [101, 102, 103, 104, 105, 106],
    "Product": ["Laptop", "Mobile", "Laptop", "Mouse", "Mobile", "Keyboard"],
    "Category": ["Electronics", "Electronics", "Electronics",
                 "Accessories", "Electronics", "Accessories"],
    "City": ["Chennai", "Chennai", "Bangalore",
             "Chennai", "Bangalore", "Chennai"],
    "Quantity": [2, 3, 1, 5, 2, 4],
    "Price": [50000, 20000, 50000, 500, 20000, 1000]
}

#inserting data into a dataframe 
df = pd.DataFrame(data)

#printing the dataframe
print(df)

   Order_ID   Product     Category       City  Quantity  Price
0       101    Laptop  Electronics    Chennai         2  50000
1       102    Mobile  Electronics    Chennai         3  20000
2       103    Laptop  Electronics  Bangalore         1  50000
3       104     Mouse  Accessories    Chennai         5    500
4       105    Mobile  Electronics  Bangalore         2  20000
5       106  Keyboard  Accessories    Chennai         4   1000

In [3]:
#Series - single column of data 
#creating a new series of columns
sales = pd.Series([10000, 20000, 15000, 30000],index=['Laptop','Mobile','Keyboard','Mouse'])
print('Sales of Products')
print(sales)

Sales of Products
Laptop      10000
Mobile      20000
Keyboard    15000
Mouse       30000
dtype: int64

In [4]:
#show the first 5 records of the dataframe
df.head()

   Order_ID Product     Category       City  Quantity  Price
0       101  Laptop  Electronics    Chennai         2  50000
1       102  Mobile  Electronics    Chennai         3  20000
2       103  Laptop  Electronics  Bangalore         1  50000
3       104   Mouse  Accessories    Chennai         5    500
4       105  Mobile  Electronics  Bangalore         2  20000

In [5]:
#show the first 3 records
df.head(3)

   Order_ID Product     Category       City  Quantity  Price
0       101  Laptop  Electronics    Chennai         2  50000
1       102  Mobile  Electronics    Chennai         3  20000
2       103  Laptop  Electronics  Bangalore         1  50000

In [6]:
#show the last 5 records of the dataframe
df.tail()

   Order_ID   Product     Category       City  Quantity  Price
1       102    Mobile  Electronics    Chennai         3  20000
2       103    Laptop  Electronics  Bangalore         1  50000
3       104     Mouse  Accessories    Chennai         5    500
4       105    Mobile  Electronics  Bangalore         2  20000
5       106  Keyboard  Accessories    Chennai         4   1000

In [7]:
#show the last 3 records of the dataframe
df.tail(3)

   Order_ID   Product     Category       City  Quantity  Price
3       104     Mouse  Accessories    Chennai         5    500
4       105    Mobile  Electronics  Bangalore         2  20000
5       106  Keyboard  Accessories    Chennai         4   1000

In [8]:
#shows the number of rows and columns
df.shape

(6, 6)

In [9]:
#shows the column names
df.columns

Index(['Order_ID', 'Product', 'Category', 'City', 'Quantity', 'Price'], dtype='str')

In [10]:
#Information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  6 non-null      int64
 1   Product   6 non-null      str
 2   Category  6 non-null      str
 3   City      6 non-null      str
 4   Quantity  6 non-null      int64
 5   Price     6 non-null      int64
dtypes: int64(3), str(3)
memory usage: 420.0 bytes

In [11]:
#Statistical summary of the dataset
df.describe()

         Order_ID  Quantity         Price
count    6.000000  6.000000      6.000000
mean   103.500000  2.833333  23583.333333
std      1.870829  1.471960  22200.037538
min    101.000000  1.000000    500.000000
25%    102.250000  2.000000   5750.000000
50%    103.500000  2.500000  20000.000000
75%    104.750000  3.750000  42500.000000
max    106.000000  5.000000  50000.000000

In [12]:
#Access single column 
print(df["Product"])

0      Laptop
1      Mobile
2      Laptop
3       Mouse
4      Mobile
5    Keyboard
Name: Product, dtype: str

In [13]:
#Accessing multiple columns
print(df[["Product", "Quantity"]])

    Product  Quantity
0    Laptop         2
1    Mobile         3
2    Laptop         1
3     Mouse         5
4    Mobile         2
5  Keyboard         4

In [14]:
#Sales = Quantity × Price
quantity = np.array(df['Quantity'])
price = np.array(df['Price'])
sales = quantity * price

print(sales)

[100000  60000  50000   2500  40000   4000]

In [15]:
df["Sales"] = sales

print(df)

   Order_ID   Product     Category       City  Quantity  Price   Sales
0       101    Laptop  Electronics    Chennai         2  50000  100000
1       102    Mobile  Electronics    Chennai         3  20000   60000
2       103    Laptop  Electronics  Bangalore         1  50000   50000
3       104     Mouse  Accessories    Chennai         5    500    2500
4       105    Mobile  Electronics  Bangalore         2  20000   40000
5       106  Keyboard  Accessories    Chennai         4   1000    4000

In [16]:
#Access using labels
print(df.loc[0, "Product"])

Laptop

In [17]:
#Access a particular row
print(df.iloc[0])

Order_ID            101
Product          Laptop
Category    Electronics
City            Chennai
Quantity              2
Price             50000
Sales            100000
Name: 0, dtype: object

In [18]:
#Access specific rows
print(df.iloc[0:3])

   Order_ID Product     Category       City  Quantity  Price   Sales
0       101  Laptop  Electronics    Chennai         2  50000  100000
1       102  Mobile  Electronics    Chennai         3  20000   60000
2       103  Laptop  Electronics  Bangalore         1  50000   50000

In [19]:
#Show me the product and quantity sold for every order
print(df[["Order_ID", "Product", "Quantity"]])

   Order_ID   Product  Quantity
0       101    Laptop         2
1       102    Mobile         3
2       103    Laptop         1
3       104     Mouse         5
4       105    Mobile         2
5       106  Keyboard         4

In [20]:
#Find laptop sales
laptop_sales = df[df['Product'] == 'Laptop']
print(laptop_sales)

   Order_ID Product     Category       City  Quantity  Price   Sales
0       101  Laptop  Electronics    Chennai         2  50000  100000
2       103  Laptop  Electronics  Bangalore         1  50000   50000

In [21]:
#Find chennai sales
chennai_sales = df[df['City'] == 'Chennai']
print(chennai_sales)

   Order_ID   Product     Category     City  Quantity  Price   Sales
0       101    Laptop  Electronics  Chennai         2  50000  100000
1       102    Mobile  Electronics  Chennai         3  20000   60000
3       104     Mouse  Accessories  Chennai         5    500    2500
5       106  Keyboard  Accessories  Chennai         4   1000    4000

In [22]:
#Quatity greater than 2
high_quantity = df[df['Quantity'] > 2]
print(high_quantity)

   Order_ID   Product     Category     City  Quantity  Price  Sales
1       102    Mobile  Electronics  Chennai         3  20000  60000
3       104     Mouse  Accessories  Chennai         5    500   2500
5       106  Keyboard  Accessories  Chennai         4   1000   4000

In [23]:
#Multiple conditions
#Find Electronics sales from Chennai
result = df[(df['Category'] == 'Electronics') & (df['City'] == 'Chennai')]
print(result)

   Order_ID Product     Category     City  Quantity  Price   Sales
0       101  Laptop  Electronics  Chennai         2  50000  100000
1       102  Mobile  Electronics  Chennai         3  20000   60000

In [24]:
#Sort by quantity
sort_by_quantity = df.sort_values('Quantity')
print(sort_by_quantity)

   Order_ID   Product     Category       City  Quantity  Price   Sales
2       103    Laptop  Electronics  Bangalore         1  50000   50000
0       101    Laptop  Electronics    Chennai         2  50000  100000
4       105    Mobile  Electronics  Bangalore         2  20000   40000
1       102    Mobile  Electronics    Chennai         3  20000   60000
5       106  Keyboard  Accessories    Chennai         4   1000    4000
3       104     Mouse  Accessories    Chennai         5    500    2500

In [25]:
#Sort by quantity (descending)
sort_by_quantity = df.sort_values('Quantity',ascending=False)
print(sort_by_quantity)

   Order_ID   Product     Category       City  Quantity  Price   Sales
3       104     Mouse  Accessories    Chennai         5    500    2500
5       106  Keyboard  Accessories    Chennai         4   1000    4000
1       102    Mobile  Electronics    Chennai         3  20000   60000
0       101    Laptop  Electronics    Chennai         2  50000  100000
4       105    Mobile  Electronics  Bangalore         2  20000   40000
2       103    Laptop  Electronics  Bangalore         1  50000   50000

In [26]:
#which order contains the highest quantity
print(df.sort_values('Quantity',ascending=False)[["Order_ID", "Product", "Quantity"]])

   Order_ID   Product  Quantity
3       104     Mouse         5
5       106  Keyboard         4
1       102    Mobile         3
0       101    Laptop         2
4       105    Mobile         2
2       103    Laptop         1

In [27]:
#Total quantity sold
total_quantity = df['Quantity'].sum()
print(total_quantity)

17

In [28]:
#Average Selling price
avg_price = df['Price'].mean()
print(f'{avg_price:.2f}')

23583.33

In [29]:
#Maximum Quantity
print(df['Quantity'].max())

5

In [30]:
#Minimum Quantity
print(df['Quantity'].min())

1

In [31]:
#Median Quantity
print(df['Quantity'].median())

2.5

In [32]:
#Number of Orders
print(df['Order_ID'].count())

6

In [33]:
#Total sales by product
product_sales = df.groupby('Product')['Sales'].sum()
print(product_sales)

Product
Keyboard      4000
Laptop      150000
Mobile      100000
Mouse         2500
Name: Sales, dtype: int64

In [34]:
#Total sales by City
city_sales = df.groupby('City')['Sales'].sum()
print(city_sales)

City
Bangalore     90000
Chennai      166500
Name: Sales, dtype: int64

In [35]:
#Quantity sold by Category
category_quantity = df.groupby('Category')['Quantity'].sum()
print(category_quantity)

Category
Accessories    9
Electronics    8
Name: Quantity, dtype: int64

In [36]:
#Multiple Statistics
result = df.groupby('Category')['Sales'].agg(['sum','mean','max'])
print(result)

                sum     mean     max
Category
Accessories    6500   3250.0    4000
Electronics  250000  62500.0  100000