# PANDAS - PANel DAta Structure

**Retail Sales Dataset**

In [1]:
#import the libraries
import pandas as pd
import numpy as np

In [2]:
#creating a dataset in a dictionary format (key = columns, values = rows)
data = {
    "Order_ID": [101, 102, 103, 104, 105, 106],
    "Product": ["Laptop", "Mobile", "Laptop", "Mouse", "Mobile", "Keyboard"],
    "Category": ["Electronics", "Electronics", "Electronics",
                 "Accessories", "Electronics", "Accessories"],
    "City": ["Chennai", "Chennai", "Bangalore",
             "Chennai", "Bangalore", "Chennai"],
    "Quantity": [2, 3, 1, 5, 2, 4],
    "Price": [50000, 20000, 50000, 500, 20000, 1000]
}

#inserting data into a dataframe 
df = pd.DataFrame(data)

#printing the dataframe
print(df)

   Order_ID   Product     Category       City  Quantity  Price
0       101    Laptop  Electronics    Chennai         2  50000
1       102    Mobile  Electronics    Chennai         3  20000
2       103    Laptop  Electronics  Bangalore         1  50000
3       104     Mouse  Accessories    Chennai         5    500
4       105    Mobile  Electronics  Bangalore         2  20000
5       106  Keyboard  Accessories    Chennai         4   1000

In [3]:
#Series - single column of data 
#creating a new series of columns
sales = pd.Series([10000, 20000, 15000, 30000],index=['Laptop','Mobile','Keyboard','Mouse'])
print('Sales of Products')
print(sales)

Sales of Products
Laptop      10000
Mobile      20000
Keyboard    15000
Mouse       30000
dtype: int64

In [4]:
#show the first 5 records of the dataframe
df.head()

   Order_ID Product     Category       City  Quantity  Price
0       101  Laptop  Electronics    Chennai         2  50000
1       102  Mobile  Electronics    Chennai         3  20000
2       103  Laptop  Electronics  Bangalore         1  50000
3       104   Mouse  Accessories    Chennai         5    500
4       105  Mobile  Electronics  Bangalore         2  20000

In [5]:
#show the first 3 records
df.head(3)

   Order_ID Product     Category       City  Quantity  Price
0       101  Laptop  Electronics    Chennai         2  50000
1       102  Mobile  Electronics    Chennai         3  20000
2       103  Laptop  Electronics  Bangalore         1  50000

In [6]:
#show the last 5 records of the dataframe
df.tail()

   Order_ID   Product     Category       City  Quantity  Price
1       102    Mobile  Electronics    Chennai         3  20000
2       103    Laptop  Electronics  Bangalore         1  50000
3       104     Mouse  Accessories    Chennai         5    500
4       105    Mobile  Electronics  Bangalore         2  20000
5       106  Keyboard  Accessories    Chennai         4   1000

In [7]:
#show the last 3 records of the dataframe
df.tail(3)

   Order_ID   Product     Category       City  Quantity  Price
3       104     Mouse  Accessories    Chennai         5    500
4       105    Mobile  Electronics  Bangalore         2  20000
5       106  Keyboard  Accessories    Chennai         4   1000

In [8]:
#shows the number of rows and columns
df.shape

(6, 6)

In [9]:
#shows the column names
df.columns

Index(['Order_ID', 'Product', 'Category', 'City', 'Quantity', 'Price'], dtype='str')

In [10]:
#Information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  6 non-null      int64
 1   Product   6 non-null      str
 2   Category  6 non-null      str
 3   City      6 non-null      str
 4   Quantity  6 non-null      int64
 5   Price     6 non-null      int64
dtypes: int64(3), str(3)
memory usage: 420.0 bytes

In [11]:
#Statistical summary of the dataset
df.describe()

         Order_ID  Quantity         Price
count    6.000000  6.000000      6.000000
mean   103.500000  2.833333  23583.333333
std      1.870829  1.471960  22200.037538
min    101.000000  1.000000    500.000000
25%    102.250000  2.000000   5750.000000
50%    103.500000  2.500000  20000.000000
75%    104.750000  3.750000  42500.000000
max    106.000000  5.000000  50000.000000

In [12]:
#Access single column 
print(df["Product"])

0      Laptop
1      Mobile
2      Laptop
3       Mouse
4      Mobile
5    Keyboard
Name: Product, dtype: str

In [13]:
#Accessing multiple columns
print(df[["Product", "Quantity"]])

    Product  Quantity
0    Laptop         2
1    Mobile         3
2    Laptop         1
3     Mouse         5
4    Mobile         2
5  Keyboard         4

In [14]:
#Sales = Quantity × Price
quantity = np.array(df['Quantity'])
price = np.array(df['Price'])
sales = quantity * price

print(sales)

[100000  60000  50000   2500  40000   4000]

In [15]:
df["Sales"] = sales

print(df)

   Order_ID   Product     Category       City  Quantity  Price   Sales
0       101    Laptop  Electronics    Chennai         2  50000  100000
1       102    Mobile  Electronics    Chennai         3  20000   60000
2       103    Laptop  Electronics  Bangalore         1  50000   50000
3       104     Mouse  Accessories    Chennai         5    500    2500
4       105    Mobile  Electronics  Bangalore         2  20000   40000
5       106  Keyboard  Accessories    Chennai         4   1000    4000

In [16]:
#Access using labels
print(df.loc[0, "Product"])

Laptop

In [17]:
#Access a particular row
print(df.iloc[0])

Order_ID            101
Product          Laptop
Category    Electronics
City            Chennai
Quantity              2
Price             50000
Sales            100000
Name: 0, dtype: object

In [18]:
#Access specific rows
print(df.iloc[0:3])

   Order_ID Product     Category       City  Quantity  Price   Sales
0       101  Laptop  Electronics    Chennai         2  50000  100000
1       102  Mobile  Electronics    Chennai         3  20000   60000
2       103  Laptop  Electronics  Bangalore         1  50000   50000

In [19]:
#Show me the product and quantity sold for every order
print(df[["Order_ID", "Product", "Quantity"]])

   Order_ID   Product  Quantity
0       101    Laptop         2
1       102    Mobile         3
2       103    Laptop         1
3       104     Mouse         5
4       105    Mobile         2
5       106  Keyboard         4

In [20]:
#Find laptop sales
laptop_sales = df[df['Product'] == 'Laptop']
print(laptop_sales)

   Order_ID Product     Category       City  Quantity  Price   Sales
0       101  Laptop  Electronics    Chennai         2  50000  100000
2       103  Laptop  Electronics  Bangalore         1  50000   50000

In [21]:
#Find chennai sales
chennai_sales = df[df['City'] == 'Chennai']
print(chennai_sales)

   Order_ID   Product     Category     City  Quantity  Price   Sales
0       101    Laptop  Electronics  Chennai         2  50000  100000
1       102    Mobile  Electronics  Chennai         3  20000   60000
3       104     Mouse  Accessories  Chennai         5    500    2500
5       106  Keyboard  Accessories  Chennai         4   1000    4000

In [22]:
#Quatity greater than 2
high_quantity = df[df['Quantity'] > 2]
print(high_quantity)

   Order_ID   Product     Category     City  Quantity  Price  Sales
1       102    Mobile  Electronics  Chennai         3  20000  60000
3       104     Mouse  Accessories  Chennai         5    500   2500
5       106  Keyboard  Accessories  Chennai         4   1000   4000

In [23]:
#Multiple conditions
#Find Electronics sales from Chennai
result = df[(df['Category'] == 'Electronics') & (df['City'] == 'Chennai')]
print(result)

   Order_ID Product     Category     City  Quantity  Price   Sales
0       101  Laptop  Electronics  Chennai         2  50000  100000
1       102  Mobile  Electronics  Chennai         3  20000   60000

In [24]:
#Sort by quantity
sort_by_quantity = df.sort_values('Quantity')
print(sort_by_quantity)

   Order_ID   Product     Category       City  Quantity  Price   Sales
2       103    Laptop  Electronics  Bangalore         1  50000   50000
0       101    Laptop  Electronics    Chennai         2  50000  100000
4       105    Mobile  Electronics  Bangalore         2  20000   40000
1       102    Mobile  Electronics    Chennai         3  20000   60000
5       106  Keyboard  Accessories    Chennai         4   1000    4000
3       104     Mouse  Accessories    Chennai         5    500    2500

In [25]:
#Sort by quantity (descending)
sort_by_quantity = df.sort_values('Quantity',ascending=False)
print(sort_by_quantity)

   Order_ID   Product     Category       City  Quantity  Price   Sales
3       104     Mouse  Accessories    Chennai         5    500    2500
5       106  Keyboard  Accessories    Chennai         4   1000    4000
1       102    Mobile  Electronics    Chennai         3  20000   60000
0       101    Laptop  Electronics    Chennai         2  50000  100000
4       105    Mobile  Electronics  Bangalore         2  20000   40000
2       103    Laptop  Electronics  Bangalore         1  50000   50000

In [26]:
#which order contains the highest quantity
print(df.sort_values('Quantity',ascending=False)[["Order_ID", "Product", "Quantity"]])

   Order_ID   Product  Quantity
3       104     Mouse         5
5       106  Keyboard         4
1       102    Mobile         3
0       101    Laptop         2
4       105    Mobile         2
2       103    Laptop         1

In [27]:
#Total quantity sold
total_quantity = df['Quantity'].sum()
print(total_quantity)

17

In [28]:
#Average Selling price
avg_price = df['Price'].mean()
print(f'{avg_price:.2f}')

23583.33

In [29]:
#Maximum Quantity
print(df['Quantity'].max())

5

In [30]:
#Minimum Quantity
print(df['Quantity'].min())

1

In [31]:
#Median Quantity
print(df['Quantity'].median())

2.5

In [32]:
#Number of Orders
print(df['Order_ID'].count())

6

In [33]:
#Total sales by product
product_sales = df.groupby('Product')['Sales'].sum()
print(product_sales)

Product
Keyboard      4000
Laptop      150000
Mobile      100000
Mouse         2500
Name: Sales, dtype: int64

In [34]:
#Total sales by City
city_sales = df.groupby('City')['Sales'].sum()
print(city_sales)

City
Bangalore     90000
Chennai      166500
Name: Sales, dtype: int64

In [35]:
#Quantity sold by Category
category_quantity = df.groupby('Category')['Quantity'].sum()
print(category_quantity)

Category
Accessories    9
Electronics    8
Name: Quantity, dtype: int64

In [36]:
#Multiple Statistics
result = df.groupby('Category')['Sales'].agg(['sum','mean','max'])
print(result)

                sum     mean     max
Category
Accessories    6500   3250.0    4000
Electronics  250000  62500.0  100000

In [37]:
#Create missing values
df_missing = df.copy()

df_missing.loc[2,'City'] = np.nan
df_missing.loc[4,'Price'] = np.nan
df_missing.loc[5,'Category'] = np.nan

df_missing

   Order_ID   Product     Category       City  Quantity    Price   Sales
0       101    Laptop  Electronics    Chennai         2  50000.0  100000
1       102    Mobile  Electronics    Chennai         3  20000.0   60000
2       103    Laptop  Electronics        NaN         1  50000.0   50000
3       104     Mouse  Accessories    Chennai         5    500.0    2500
4       105    Mobile  Electronics  Bangalore         2      NaN   40000
5       106  Keyboard          NaN    Chennai         4   1000.0    4000

In [38]:
#Find the number of missing values in each column
df_missing.isnull().sum()

Order_ID    0
Product     0
Category    1
City        1
Quantity    0
Price       1
Sales       0
dtype: int64

In [39]:
#Display only the rows containing missing values
df_missing[df_missing.isnull().any(axis=1)]

   Order_ID   Product     Category       City  Quantity    Price  Sales
2       103    Laptop  Electronics        NaN         1  50000.0  50000
4       105    Mobile  Electronics  Bangalore         2      NaN  40000
5       106  Keyboard          NaN    Chennai         4   1000.0   4000

In [40]:
#Fill missing City with "Unknown"
df_missing['City'] = df_missing['City'].fillna('Unknown')

df_missing.loc[2,'City']

'Unknown'

In [41]:
#Fill missing Category with "Unknown"
df_missing['Category'] = df_missing['Category'].fillna('Unknown')

df_missing.loc[5,'Category']

'Unknown'

In [42]:
#Replace missing Price with the average price
df_missing['Price'] = df_missing['Price'].fillna(df_missing['Price'].mean())

df_missing.loc[4,'Price'].item()

24300.0

In [43]:
#Verify that no missing values remain
df_missing[df_missing.notnull().all(axis = 1)]

   Order_ID   Product     Category       City  Quantity    Price   Sales
0       101    Laptop  Electronics    Chennai         2  50000.0  100000
1       102    Mobile  Electronics    Chennai         3  20000.0   60000
2       103    Laptop  Electronics    Unknown         1  50000.0   50000
3       104     Mouse  Accessories    Chennai         5    500.0    2500
4       105    Mobile  Electronics  Bangalore         2  24300.0   40000
5       106  Keyboard      Unknown    Chennai         4   1000.0    4000

In [44]:
#Create a Discount column with a 10% discount
df['Discount'] = df['Price'] * 0.10
df

,Order_ID,Product,Category,City,Quantity,Price,Sales,Discount
0,101,Laptop,Electronics,Chennai,2,50000,100000,5000.0
1,102,Mobile,Electronics,Chennai,3,20000,60000,2000.0
2,103,Laptop,Electronics,Bangalore,1,50000,50000,5000.0
3,104,Mouse,Accessories,Chennai,5,500,2500,50.0
4,105,Mobile,Electronics,Bangalore,2,20000,40000,2000.0
5,106,Keyboard,Accessories,Chennai,4,1000,4000,100.0

In [45]:
#Final_Amount = Total_Amount - Discount
df['Final_amount'] = df['Price'] - df['Discount']

df

,Order_ID,Product,Category,City,Quantity,Price,Sales,Discount,Final_amount
0,101,Laptop,Electronics,Chennai,2,50000,100000,5000.0,45000.0
1,102,Mobile,Electronics,Chennai,3,20000,60000,2000.0,18000.0
2,103,Laptop,Electronics,Bangalore,1,50000,50000,5000.0,45000.0
3,104,Mouse,Accessories,Chennai,5,500,2500,50.0,450.0
4,105,Mobile,Electronics,Bangalore,2,20000,40000,2000.0,18000.0
5,106,Keyboard,Accessories,Chennai,4,1000,4000,100.0,900.0

In [46]:
#Remove the Discount column
df.drop('Discount', axis=1 , inplace = True)

df

,Order_ID,Product,Category,City,Quantity,Price,Sales,Final_amount
0,101,Laptop,Electronics,Chennai,2,50000,100000,45000.0
1,102,Mobile,Electronics,Chennai,3,20000,60000,18000.0
2,103,Laptop,Electronics,Bangalore,1,50000,50000,45000.0
3,104,Mouse,Accessories,Chennai,5,500,2500,450.0
4,105,Mobile,Electronics,Bangalore,2,20000,40000,18000.0
5,106,Keyboard,Accessories,Chennai,4,1000,4000,900.0

In [47]:
#Renaming the columns
df.rename(columns={
    "Order_ID": "OrderID",
    "Price": "Unit_Price",
    "Category": "Product_Category"
}, inplace=True)

df

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount
0,101,Laptop,Electronics,Chennai,2,50000,100000,45000.0
1,102,Mobile,Electronics,Chennai,3,20000,60000,18000.0
2,103,Laptop,Electronics,Bangalore,1,50000,50000,45000.0
3,104,Mouse,Accessories,Chennai,5,500,2500,450.0
4,105,Mobile,Electronics,Bangalore,2,20000,40000,18000.0
5,106,Keyboard,Accessories,Chennai,4,1000,4000,900.0

In [48]:
#Save the dataframe as retail_sales.csv
df.to_csv('retail_orders.csv', index=False)

In [49]:
#Read CSV file
df_csv = pd.read_csv('retail_orders.csv')

df_csv

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount
0,101,Laptop,Electronics,Chennai,2,50000,100000,45000.0
1,102,Mobile,Electronics,Chennai,3,20000,60000,18000.0
2,103,Laptop,Electronics,Bangalore,1,50000,50000,45000.0
3,104,Mouse,Accessories,Chennai,5,500,2500,450.0
4,105,Mobile,Electronics,Bangalore,2,20000,40000,18000.0
5,106,Keyboard,Accessories,Chennai,4,1000,4000,900.0

In [50]:
df_csv.shape

(6, 8)

In [51]:
df_csv.columns

Index(['OrderID', 'Product', 'Product_Category', 'City', 'Quantity',
       'Unit_Price', 'Sales', 'Final_amount'],
      dtype='str')

In [52]:
df_csv.dtypes

OrderID               int64
Product                 str
Product_Category        str
City                    str
Quantity              int64
Unit_Price            int64
Sales                 int64
Final_amount        float64
dtype: object

In [53]:
df_csv.head()

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount
0,101,Laptop,Electronics,Chennai,2,50000,100000,45000.0
1,102,Mobile,Electronics,Chennai,3,20000,60000,18000.0
2,103,Laptop,Electronics,Bangalore,1,50000,50000,45000.0
3,104,Mouse,Accessories,Chennai,5,500,2500,450.0
4,105,Mobile,Electronics,Bangalore,2,20000,40000,18000.0

In [54]:
df_types = df.copy()

df_types['Quantity'] = df_types['Quantity'].astype(str)
df_types['Sales'] = df_types['Sales'].astype(str)

df_types.dtypes

OrderID               int64
Product                 str
Product_Category        str
City                    str
Quantity                str
Unit_Price            int64
Sales                   str
Final_amount        float64
dtype: object

In [55]:
df_types['Quantity'] = df_types['Quantity'].astype(int)
df_types['Sales'] = df_types['Sales'].astype(float)

df_types.dtypes

OrderID               int64
Product                 str
Product_Category        str
City                    str
Quantity              int64
Unit_Price            int64
Sales               float64
Final_amount        float64
dtype: object

In [56]:
#String Operations
df_String = df.copy()

df_String['Product'].str.upper()

0      LAPTOP
1      MOBILE
2      LAPTOP
3       MOUSE
4      MOBILE
5    KEYBOARD
Name: Product, dtype: str

In [57]:
#String lowercase
df_String['City'].str.lower()

0      chennai
1      chennai
2    bangalore
3      chennai
4    bangalore
5      chennai
Name: City, dtype: str

In [58]:
#Filter Product with String contains values
df_String[df_String["Product"].str.contains("Mobile")]

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount
1,102,Mobile,Electronics,Chennai,3,20000,60000,18000.0
4,105,Mobile,Electronics,Bangalore,2,20000,40000,18000.0

In [59]:
#Find String whose length is greater than 6
df_String[df_String["Product"].str.len() > 6]

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount
5,106,Keyboard,Accessories,Chennai,4,1000,4000,900.0

In [60]:
#Replace String
df_String["Product"].str.replace("Mouse", "Wireless Mouse")

0            Laptop
1            Mobile
2            Laptop
3    Wireless Mouse
4            Mobile
5          Keyboard
Name: Product, dtype: str

In [61]:
#Create a customer data and add it to pandas DataFrame
customer_data = {
    "Order_ID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Anu", "Bala", "Chitra", "Deepak", "Elena", "Farhan"],
    "Payment_Mode": ["UPI", "Card", "UPI", "Cash", "Card", "UPI"]
}

customer_df = pd.DataFrame(customer_data)

customer_df

   Order_ID Customer Payment_Mode
0       101      Anu          UPI
1       102     Bala         Card
2       103   Chitra          UPI
3       104   Deepak         Cash
4       105    Elena         Card
5       106   Farhan          UPI

In [62]:
#convert order Id column name using rename
customer_df.rename(columns={'Order_ID':'OrderID'}, inplace=True)
customer_df

   OrderID Customer Payment_Mode
0      101      Anu          UPI
1      102     Bala         Card
2      103   Chitra          UPI
3      104   Deepak         Cash
4      105    Elena         Card
5      106   Farhan          UPI

In [63]:
df = df.drop(3)

In [64]:
#Inner Merge
merged_df = pd.merge(
    df,
    customer_df,
    on="OrderID",
    how="inner"
)

merged_df

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount,Customer,Payment_Mode
0,101,Laptop,Electronics,Chennai,2,50000,100000,45000.0,Anu,UPI
1,102,Mobile,Electronics,Chennai,3,20000,60000,18000.0,Bala,Card
2,103,Laptop,Electronics,Bangalore,1,50000,50000,45000.0,Chitra,UPI
3,105,Mobile,Electronics,Bangalore,2,20000,40000,18000.0,Elena,Card
4,106,Keyboard,Accessories,Chennai,4,1000,4000,900.0,Farhan,UPI

In [65]:
#Left Merge
merged_df = pd.merge(
    df,
    customer_df,
    on="OrderID",
    how="left"
)

merged_df

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount,Customer,Payment_Mode
0,101,Laptop,Electronics,Chennai,2,50000,100000,45000.0,Anu,UPI
1,102,Mobile,Electronics,Chennai,3,20000,60000,18000.0,Bala,Card
2,103,Laptop,Electronics,Bangalore,1,50000,50000,45000.0,Chitra,UPI
3,105,Mobile,Electronics,Bangalore,2,20000,40000,18000.0,Elena,Card
4,106,Keyboard,Accessories,Chennai,4,1000,4000,900.0,Farhan,UPI

In [66]:
#Right Merge
merged_df = pd.merge(
    df,
    customer_df,
    on="OrderID",
    how="right"
)

merged_df

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount,Customer,Payment_Mode
0,101,Laptop,Electronics,Chennai,2.0,50000.0,100000.0,45000.0,Anu,UPI
1,102,Mobile,Electronics,Chennai,3.0,20000.0,60000.0,18000.0,Bala,Card
2,103,Laptop,Electronics,Bangalore,1.0,50000.0,50000.0,45000.0,Chitra,UPI
3,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deepak,Cash
4,105,Mobile,Electronics,Bangalore,2.0,20000.0,40000.0,18000.0,Elena,Card
5,106,Keyboard,Accessories,Chennai,4.0,1000.0,4000.0,900.0,Farhan,UPI

In [67]:
#Outer Merge
merged_df = pd.merge(
    df,
    customer_df,
    on="OrderID",
    how="outer"
)

merged_df

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount,Customer,Payment_Mode
0,101,Laptop,Electronics,Chennai,2.0,50000.0,100000.0,45000.0,Anu,UPI
1,102,Mobile,Electronics,Chennai,3.0,20000.0,60000.0,18000.0,Bala,Card
2,103,Laptop,Electronics,Bangalore,1.0,50000.0,50000.0,45000.0,Chitra,UPI
3,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deepak,Cash
4,105,Mobile,Electronics,Bangalore,2.0,20000.0,40000.0,18000.0,Elena,Card
5,106,Keyboard,Accessories,Chennai,4.0,1000.0,4000.0,900.0,Farhan,UPI

In [68]:
#Concatenating Dataframes
#Create new order
new_data = {
    "Order_ID": [107, 108, 109],
    "Product": ["Monitor", "Mobile", "Keyboard"],
    "Category": ["Electronics", "Electronics", "Accessories"],
    "City": ["Chennai", "Bangalore", "Chennai"],
    "Quantity": [2, 1, 3],
    "Price": [12000, 25000, 1500]
}

df_new = pd.DataFrame(new_data)

df_new

   Order_ID   Product     Category       City  Quantity  Price
0       107   Monitor  Electronics    Chennai         2  12000
1       108    Mobile  Electronics  Bangalore         1  25000
2       109  Keyboard  Accessories    Chennai         3   1500

In [69]:
all_orders = pd.concat([df, df_new], ignore_index=True)

all_orders

,OrderID,Product,Product_Category,City,Quantity,Unit_Price,Sales,Final_amount,Order_ID,Category,Price
0,101.0,Laptop,Electronics,Chennai,2,50000.0,100000.0,45000.0,NaN,NaN,NaN
1,102.0,Mobile,Electronics,Chennai,3,20000.0,60000.0,18000.0,NaN,NaN,NaN
2,103.0,Laptop,Electronics,Bangalore,1,50000.0,50000.0,45000.0,NaN,NaN,NaN
3,105.0,Mobile,Electronics,Bangalore,2,20000.0,40000.0,18000.0,NaN,NaN,NaN
4,106.0,Keyboard,Accessories,Chennai,4,1000.0,4000.0,900.0,NaN,NaN,NaN
5,NaN,Monitor,NaN,Chennai,2,NaN,NaN,NaN,107.0,Electronics,12000.0
6,NaN,Mobile,NaN,Bangalore,1,NaN,NaN,NaN,108.0,Electronics,25000.0
7,NaN,Keyboard,NaN,Chennai,3,NaN,NaN,NaN,109.0,Accessories,1500.0

In [70]:
#Concatenate columns
#Create two dataframes
order_ids = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104, 105, 106]
})

delivery = pd.DataFrame({
    "Delivery_Status": [
        "Delivered",
        "Shipped",
        "Delivered",
        "Processing",
        "Shipped",
        "Delivered"
    ]
})

In [71]:
order_ids

   Order_ID
0       101
1       102
2       103
3       104
4       105
5       106

In [72]:
delivery

  Delivery_Status
0       Delivered
1         Shipped
2       Delivered
3      Processing
4         Shipped
5       Delivered

In [73]:
#Concat Columns of two dataframes
result = pd.concat(
    [order_ids, delivery],
    axis=1
)

result

   Order_ID Delivery_Status
0       101       Delivered
1       102         Shipped
2       103       Delivered
3       104      Processing
4       105         Shipped
5       106       Delivered